#!/bin/bash
#Author F@lcOn, make 03.2020
#Скрипт делает бэкап MariaDB на лету не блокируя базы
#restore https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/ 

cur_date=$(date +%Y-%m-%d:%H:%M:%S)
back_dir=/home/zabbix_backup/
log=${back_dir}backup_${cur_date}.log
user=root
passwd=1qazxdr5

if ! [ -d $back_dir ]; then
mkdir $back_dir
fi

echo "-= Start BackUp MariaDB =-" &> $log

mariabackup --backup --target-dir=${back_dir}zbackup_${cur_date}/ --user=$user --password=$passwd  &>> $log

echo "-= End BackUp MariaDB =-" &>> $log

echo "-= Start archive BackUp  =-" &>> $log

tar -czvf ${back_dir}zbackup_${cur_date}.tgz ${back_dir}zbackup_${cur_date} &>> $log

echo "-= End archive BackUp  =-" &>> $log

echo "-= BackUp /etc/zabbix & /usr/share/zabbix =-" &>> $log

tar -czvf ${back_dir}z_etc_usr_backup_${cur_date}.tgz /etc/zabbix/ /usr/share/zabbix &>> $log

echo "-= End BackUp /etc/zabbix & /usr/share/zabbix =-" &>> $log

echo "-= Remove BackUp directory =-" &>> $log

rm -rf ${back_dir}zbackup_${cur_date}  &>> $log

echo "-= Remove BackUp directory OK =-" &>> $log

echo "-= Remove backup archives over 7 days =-" &>> $log

find $back_dir -type f -mtime +7 -exec rm -rf {} \; &>> $log

echo "-= Remove backup archives over 7 days OK =-" &>> $log

echo "-= End BackUp MariaDB =-" &>> $log
